language: c
sudo: required
compiler: gcc
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y cmake

script:
  - cmake ./travis/CMakeLists.txt 
  - cd ./travis/ && make
  - ./stack "5 5 /"
  - ./stack "5 1 2 + 4 x + 3 - 2 /"
