language: c
sudo: required
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y gcc-5 cmake

script:
  - cmake && make
  - ./stack