language: c
sudo: required
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y gcc cmake

script:
  - cmake CMakeLists.txt && make
  - ./stack "5 5 /"
  - ./stack "5 1 2 + 4 x + 3 - 2 /"
