language: c
sudo: required
compiler: gcc
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y cmake

script:
  - sed -ie 's/^#add/add/' CMakeLists.txt
  - cmake CMakeLists.txt && make
  - ./stack "5 5 /"
  - ./stack "5 1 2 + 4 x + 3 - 2 /"
